# Criando o DataFrame de Turmas do BTI entre 2013 e 2024

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

In [15]:
#carregando o dataframe principal
turmas_bti = pd.read_csv('../databases/turmas.csv')
#carregando o dataframe secundário, vamos usar algumas colunas dele 
comp_curr_bti = pd.read_csv('../databases/comp_curr_BTI.csv')

C:\Users\marie\AppData\Local\Temp\ipykernel_15676\3615335296.py:2: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  turmas_bti = pd.read_csv('../databases/turmas.csv')

In [ ]:
#visualização do df
turmas_bti

,id_turma,codigo_turma,siape,matricula_docente_externo,observacao,id_componente_curricular,ch_dedicada_periodo,nivel_ensino,campus_turma,local,...,capacidade_aluno,tipo,distancia,data_consolidacao,agrupadora,id_turma_agrupadora,qtd_aulas_lancadas,situacao_turma,convenio,modalidade_participantes
0,1204204,01,1665448.0,NaN,NaN,41147,30,STRICTO SENSU,NaN,sala da base,...,2.0,REGULAR,False,NaN,False,NaN,NaN,EXCLUÍDA,NaN,Presencial
1,1204205,02,6349464.0,NaN,NaN,41147,30,STRICTO SENSU,NaN,sala da base,...,2.0,REGULAR,False,NaN,False,NaN,NaN,EXCLUÍDA,NaN,Presencial
2,1204206,03,1149551.0,NaN,NaN,41147,30,STRICTO SENSU,NaN,sala da base,...,1.0,REGULAR,False,NaN,False,NaN,NaN,EXCLUÍDA,NaN,Presencial
3,1204207,04,1323908.0,NaN,NaN,41147,30,STRICTO SENSU,NaN,sala da base,...,3.0,REGULAR,False,NaN,False,NaN,NaN,EXCLUÍDA,NaN,Presencial
4,1204208,05,414674.0,NaN,NaN,41147,30,STRICTO SENSU,NaN,sala da base,...,1.0,REGULAR,False,NaN,False,NaN,NaN,EXCLUÍDA,NaN,Presencial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336866,57581498,02,NaN,12023.0,NaN,56663,60,TÉCNICO,NaN,IMD,...,40.0,REGULAR,False,2016/02/03 16:07:32.646000000,False,NaN,0.0,CONSOLIDADA,NaN,Presencial
336867,57587745,01,1506238.0,NaN,NaN,61996,45,RESIDÊNCIA,NaN,huab,...,50.0,REGULAR,False,2016/06/18 19:41:00.143000000,False,NaN,0.0,CONSOLIDADA,NaN,Presencial
336868,57592862,01,1321136.0,NaN,NaN,54518,20,LATO SENSU,NaN,AUDITORIO DE PSICOLOGIA,...,50.0,REGULAR,False,2016/08/19 23:28:36.075000000,False,NaN,0.0,CONSOLIDADA,NaN,Presencial
336869,57592875,01,2330188.0,NaN,NaN,63332,20,LATO SENSU,NaN,auditório de psicologia,...,50.0,REGULAR,False,2016/08/22 12:16:51.345000000,False,NaN,0.0,CONSOLIDADA,NaN,Presencial
336870,57643253,03,NaN,12108.0,NaN,57335,60,TÉCNICO,NaN,TOUROS,...,40.0,REGULAR,False,2019/05/02 10:35:29.609000000,False,NaN,0.0,CONSOLIDADA,NaN,Presencial

In [ ]:
#dropando colunas irrelevantes p/ nossa análise
turmas_bti = turmas_bti.drop(['matricula_docente_externo', 'observacao', 'campus_turma', 'local', 'data_inicio', 'data_fim', 'distancia', 'data_consolidacao', 'agrupadora', 'id_turma_agrupadora', 'convenio', 'modalidade_participantes'], axis=1)

turmas_bti

,id_turma,codigo_turma,siape,id_componente_curricular,ch_dedicada_periodo,nivel_ensino,ano,periodo,descricao_horario,total_solicitacoes,capacidade_aluno,tipo,qtd_aulas_lancadas,situacao_turma
0,1204204,01,1665448.0,41147,30,STRICTO SENSU,2013,2,2M12,NaN,2.0,REGULAR,NaN,EXCLUÍDA
1,1204205,02,6349464.0,41147,30,STRICTO SENSU,2013,2,5M34,NaN,2.0,REGULAR,NaN,EXCLUÍDA
2,1204206,03,1149551.0,41147,30,STRICTO SENSU,2013,2,2M12,NaN,1.0,REGULAR,NaN,EXCLUÍDA
3,1204207,04,1323908.0,41147,30,STRICTO SENSU,2013,2,2M12,NaN,3.0,REGULAR,NaN,EXCLUÍDA
4,1204208,05,414674.0,41147,30,STRICTO SENSU,2013,2,2M12,NaN,1.0,REGULAR,NaN,EXCLUÍDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336866,57581498,02,NaN,56663,60,TÉCNICO,2014,1,2356T12,NaN,40.0,REGULAR,0.0,CONSOLIDADA
336867,57587745,01,1506238.0,61996,45,RESIDÊNCIA,2014,1,6M123,NaN,50.0,REGULAR,0.0,CONSOLIDADA
336868,57592862,01,1321136.0,54518,20,LATO SENSU,2014,1,16M2345 7M234 67T3456,NaN,50.0,REGULAR,0.0,CONSOLIDADA
336869,57592875,01,2330188.0,63332,20,LATO SENSU,2014,1,167M2345 67T3456,NaN,50.0,REGULAR,0.0,CONSOLIDADA
336870,57643253,03,NaN,57335,60,TÉCNICO,2014,1,23N23,NaN,40.0,REGULAR,0.0,CONSOLIDADA

In [ ]:
#apenas turmas de graduação
turmas_bti = turmas_bti[turmas_bti['nivel_ensino'] == 'GRADUAÇÃO']
#apenas turmas regulares
turmas_bti = turmas_bti[turmas_bti['tipo'] == 'REGULAR']

turmas_bti

,id_turma,codigo_turma,siape,id_componente_curricular,ch_dedicada_periodo,nivel_ensino,ano,periodo,descricao_horario,total_solicitacoes,capacidade_aluno,tipo,qtd_aulas_lancadas,situacao_turma
91,1206694,14,1163184.0,2046772,0,GRADUAÇÃO,2013,2,NaN,28.0,NaN,REGULAR,NaN,CONSOLIDADA
92,1206695,02,1163184.0,2046772,0,GRADUAÇÃO,2013,2,NaN,7.0,NaN,REGULAR,NaN,CONSOLIDADA
93,1206696,20,1163184.0,2046772,0,GRADUAÇÃO,2013,2,NaN,29.0,NaN,REGULAR,NaN,CONSOLIDADA
94,1206697,12,1163184.0,2046772,0,GRADUAÇÃO,2013,2,NaN,39.0,NaN,REGULAR,NaN,CONSOLIDADA
95,1206698,01,1163184.0,2046772,0,GRADUAÇÃO,2013,2,NaN,21.0,NaN,REGULAR,NaN,CONSOLIDADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336685,1235270,14,2378532.0,52074,0,GRADUAÇÃO,2014,1,NaN,NaN,NaN,REGULAR,NaN,EXCLUÍDA
336686,1235271,26,2378532.0,52074,0,GRADUAÇÃO,2014,1,NaN,NaN,NaN,REGULAR,NaN,EXCLUÍDA
336687,1235272,17,2378532.0,52074,0,GRADUAÇÃO,2014,1,NaN,NaN,NaN,REGULAR,NaN,EXCLUÍDA
336688,1235273,25,2378532.0,52074,0,GRADUAÇÃO,2014,1,NaN,NaN,NaN,REGULAR,NaN,EXCLUÍDA
336689,1235274,24,2378532.0,52074,0,GRADUAÇÃO,2014,1,NaN,NaN,NaN,REGULAR,NaN,EXCLUÍDA

In [ ]:
#filtrando id_componente_curricular para manter no df apenas componentes curriculares ofertados ao bti
turmas_bti = turmas_bti[turmas_bti['id_componente_curricular'].isin(comp_curr_bti['id_componente'])]

turmas_bti

,id_turma,codigo_turma,siape,id_componente_curricular,ch_dedicada_periodo,nivel_ensino,ano,periodo,descricao_horario,total_solicitacoes,capacidade_aluno,tipo,qtd_aulas_lancadas,situacao_turma
1670,1208017,01,1495704.0,25247,60,GRADUAÇÃO,2013,2,35M56,25.0,41.0,REGULAR,NaN,CONSOLIDADA
1672,1208019,02,1350250.0,25247,60,GRADUAÇÃO,2013,2,35T12,49.0,40.0,REGULAR,NaN,CONSOLIDADA
1694,1208040,01,2524467.0,21781,60,GRADUAÇÃO,2013,2,24M34,23.0,40.0,REGULAR,NaN,CONSOLIDADA
1705,1208051,01,3366375.0,25248,60,GRADUAÇÃO,2013,2,24T56,51.0,35.0,REGULAR,NaN,CONSOLIDADA
2236,1208531,01,1201268.0,21752,60,GRADUAÇÃO,2013,2,2M1234,4.0,1.0,REGULAR,NaN,CONSOLIDADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332531,1224598,03,347031.0,23499,90,GRADUAÇÃO,2014,1,246M12,42.0,40.0,REGULAR,106.0,CONSOLIDADA
332532,1224599,10,350518.0,25247,60,GRADUAÇÃO,2014,1,35M56,10.0,40.0,REGULAR,72.0,CONSOLIDADA
332533,1224600,11,2497950.0,25247,60,GRADUAÇÃO,2014,1,35M56,20.0,40.0,REGULAR,68.0,CONSOLIDADA
332534,1224601,04,2859606.0,21753,60,GRADUAÇÃO,2014,1,35M12,41.0,40.0,REGULAR,84.0,CONSOLIDADA
334103,1225654,01,346494.0,55226,60,GRADUAÇÃO,2014,1,6M2345,7.0,10.0,REGULAR,72.0,CONSOLIDADA

In [ ]:
#unindo colunas 'id_componente', 'codigo' e 'nome' de comp_curr_bti no df turmas_bti, join na coluna de 'id_componente'
turmas_bti = turmas_bti.merge(comp_curr_bti[['id_componente', 'codigo', 'nome']], left_on='id_componente_curricular', right_on='id_componente', how='left')

turmas_bti

,id_turma,codigo_turma,siape,id_componente_curricular,ch_dedicada_periodo,nivel_ensino,ano,periodo,descricao_horario,total_solicitacoes,capacidade_aluno,tipo,qtd_aulas_lancadas,situacao_turma,id_componente,codigo,nome
0,1208017,01,1495704.0,25247,60,GRADUAÇÃO,2013,2,35M56,25.0,41.0,REGULAR,NaN,CONSOLIDADA,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES
1,1208019,02,1350250.0,25247,60,GRADUAÇÃO,2013,2,35T12,49.0,40.0,REGULAR,NaN,CONSOLIDADA,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES
2,1208040,01,2524467.0,21781,60,GRADUAÇÃO,2013,2,24M34,23.0,40.0,REGULAR,NaN,CONSOLIDADA,21781,DIM0440,INTELIGENCIA ARTIFICIAL
3,1208051,01,3366375.0,25248,60,GRADUAÇÃO,2013,2,24T56,51.0,35.0,REGULAR,NaN,CONSOLIDADA,25248,DIM0103,INTRODUCAO A INFORMATICA
4,1208531,01,1201268.0,21752,60,GRADUAÇÃO,2013,2,2M1234,4.0,1.0,REGULAR,NaN,CONSOLIDADA,21752,DIM0335,APLIC.DE GRAFOS A EXPLOR.E DISTRIB.DO PETROLEO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3704,1224598,03,347031.0,23499,90,GRADUAÇÃO,2014,1,246M12,42.0,40.0,REGULAR,106.0,CONSOLIDADA,23499,DIM0040,CALCULO NUMERICO
3705,1224599,10,350518.0,25247,60,GRADUAÇÃO,2014,1,35M56,10.0,40.0,REGULAR,72.0,CONSOLIDADA,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES
3706,1224600,11,2497950.0,25247,60,GRADUAÇÃO,2014,1,35M56,20.0,40.0,REGULAR,68.0,CONSOLIDADA,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES
3707,1224601,04,2859606.0,21753,60,GRADUAÇÃO,2014,1,35M12,41.0,40.0,REGULAR,84.0,CONSOLIDADA,21753,DIM0321,LINGUAGENS DE PROGRAMAÇÃO
3708,1225654,01,346494.0,55226,60,GRADUAÇÃO,2014,1,6M2345,7.0,10.0,REGULAR,72.0,CONSOLIDADA,55226,DIM0112,NOÇÕES DE ALGORITMO E PROGRAMAÇÃO

In [ ]:
#dropando outras colunas irrelevantes
turmas_bti.drop(['id_componente', 'tipo', 'nivel_ensino', 'qtd_aulas_lancadas'], axis=1)
#reorganizando a ordem das colunas
turmas_bti = turmas_bti[['id_turma', 'codigo_turma', 'id_componente', 'codigo', 'nome', 'siape', 'ch_dedicada_periodo', 'ano', 'periodo', 'descricao_horario', 'situacao_turma', 'capacidade_aluno', 'total_solicitacoes']]

turmas_bti

,id_turma,codigo_turma,id_componente,codigo,nome,siape,ch_dedicada_periodo,ano,periodo,descricao_horario,situacao_turma,capacidade_aluno,total_solicitacoes
0,1208017,01,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES,1495704.0,60,2013,2,35M56,CONSOLIDADA,41.0,25.0
1,1208019,02,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES,1350250.0,60,2013,2,35T12,CONSOLIDADA,40.0,49.0
2,1208040,01,21781,DIM0440,INTELIGENCIA ARTIFICIAL,2524467.0,60,2013,2,24M34,CONSOLIDADA,40.0,23.0
3,1208051,01,25248,DIM0103,INTRODUCAO A INFORMATICA,3366375.0,60,2013,2,24T56,CONSOLIDADA,35.0,51.0
4,1208531,01,21752,DIM0335,APLIC.DE GRAFOS A EXPLOR.E DISTRIB.DO PETROLEO,1201268.0,60,2013,2,2M1234,CONSOLIDADA,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3704,1224598,03,23499,DIM0040,CALCULO NUMERICO,347031.0,90,2014,1,246M12,CONSOLIDADA,40.0,42.0
3705,1224599,10,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES,350518.0,60,2014,1,35M56,CONSOLIDADA,40.0,10.0
3706,1224600,11,25247,DIM0320,ALGORITMO E PROGRAMACAO DE COMPUTADORES,2497950.0,60,2014,1,35M56,CONSOLIDADA,40.0,20.0
3707,1224601,04,21753,DIM0321,LINGUAGENS DE PROGRAMAÇÃO,2859606.0,60,2014,1,35M12,CONSOLIDADA,40.0,41.0
3708,1225654,01,55226,DIM0112,NOÇÕES DE ALGORITMO E PROGRAMAÇÃO,346494.0,60,2014,1,6M2345,CONSOLIDADA,10.0,7.0

In [ ]:
#exportando para csv com sep=';', prefiro assim !
turmas_bti.to_csv('../databases/turmas_bti.csv', sep=';')

Temos um dataset com turmas regulares ofertadas ao BTI (com código DIM ou IMD) entre 2013 e 2024.